# Generated by Django 4.1.3 on 2022-11-24 00:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=70, verbose_name='ФИО')),
                ('description', models.TextField(max_length=500, verbose_name='Описание')),
                ('age', models.PositiveSmallIntegerField(default=0, verbose_name='Возраст')),
                ('image', models.ImageField(upload_to='actors/', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Актёр и режисёр',
                'verbose_name_plural': 'Актёры и режисёры',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название фильма')),
                ('description', models.TextField(max_length=500, verbose_name='Описание фильма')),
                ('poster', models.ImageField(upload_to='movie_poster/', verbose_name='Постер фильма')),
                ('movie_trailer', models.FileField(upload_to='movie_trailer/', verbose_name='Трейлер фильма')),
                ('movie_file', models.FileField(upload_to='movie_file/', verbose_name='Файл фильма')),
                ('year', models.DateField(default=datetime.date.today, verbose_name='Дата выпуска')),
                ('running_time', models.CharField(max_length=10, verbose_name='Длительность фильма')),
                ('country', models.CharField(max_length=30, verbose_name='Страна')),
                ('draft', models.BooleanField(default=False, verbose_name='Черновик')),
                ('actors', models.ManyToManyField(related_name='film_actor', to='movies.actor', verbose_name='Актёр')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.category', verbose_name='Категория')),
                ('directors', models.ManyToManyField(related_name='film_director', to='movies.actor', verbose_name='Режисёр')),
                ('genres', models.ManyToManyField(to='categories.genre', verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
            },
        ),
    ]
