# Generated by Django 4.1.3 on 2022-12-22 23:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_gallery'),
        ('users', '0002_alter_user_email_alter_user_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchedMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched_movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watched_movie', to='movies.movie')),
                ('watched_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watched_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
