# Generated by Django 4.1.3 on 2023-02-23 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='102806976_t1kbCQj.jpg', null=True, upload_to='profile_image/'),
        ),
    ]
