# Generated by Django 4.1.3 on 2022-11-23 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_us',
            name='description',
            field=models.TextField(max_length=500, verbose_name='О нас текст'),
        ),
    ]
